name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: airsquared/setup-java@master
        with:
          java-version: 1.8
          javafx: true

      - name: Run tests with maven
        run: mvn --batch-mode --update-snapshots test
